CREATE DATABASE QuanLyBanHang
USE QuanLyBanHang
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) ,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH smalldatetime,
	DOANHSO money,
	NGDK smalldatetime
	CONSTRAINT PK_KH primary key (MAKH)
)
--- Tao bang NHANVIEN ---
CREATE TABLE NHANVIEN
(
	MANV CHAR(4),
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL smalldatetime,
	CONSTRAINT PK_NV PRIMARY KEY (MANV)
)

CREATE TABLE SANPHAM
(
	MASP CHAR(4),
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY,
	CONSTRAINT PK_SP PRIMARY KEY(MASP)
)
CREATE TABLE HOADON
(
	SOHD INT,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	CONSTRAINT FK_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
	CONSTRAINT FK_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
	TRIGIA MONEY,
	CONSTRAINT PK_HD PRIMARY KEY(SOHD)
)
CREATE TABLE CTHD
(
	SOHD INT,
	MASP CHAR(4),
	SL INT,
	CONSTRAINT PK_SOHD PRIMARY KEY(SOHD,MASP),
	CONSTRAINT FK_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD),
	CONSTRAINT FK_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
)
use QuanLyBanHang

--- CAU 2 ---
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)
--- CAU 3 ---
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT
--- CAU 4 --- 
ALTER TABLE SANPHAM 
ALTER COLUMN GHICHU VARCHAR(100)

--- CAU 5 ---
ALTER TABLE SANPHAM
DROP COLUMN GHICHU
--- CAU 6 ---
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_LOAIKH CHECK (LOAIKH = 'Vang Lai' or LOAIKH = 'Thuong Xuyen' or LOAIKH = 'Vip')

--- CAU 7 ---
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DVT CHECK (DVT = 'cay' or DVT = 'hop' or DVT = 'cai' or DVT = 'quyen' or DVT = 'chuc')

--- CAU 8 ---
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GIABAN CHECK (GIA >= 500)

--- CAU 9 ---
ALTER TABLE CTHD
ADD CONSTRAINT CK_CTHD CHECK (SL >= 1)

--- CAU 10 ---
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGDK CHECK (NGDK > NGSINH)


USE master
CREATE DATABASE QuanLyGiaoVu
USE QuanLyGiaoVu

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4),
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4),
	CONSTRAINT PK_GV PRIMARY KEY (MAGV)
)

CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4),
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
	CONSTRAINT PK_K PRIMARY KEY (MAKHOA),
	CONSTRAINT FK_TRGKHOA FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN (MAGV)

)

CREATE TABLE MONHOC
(
	MAMH VARCHAR(10),
	TENMH VARCHAR(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA VARCHAR(4),
	CONSTRAINT PK_MAMH PRIMARY KEY (MAMH),
	CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
)

CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10)
)

CREATE TABLE HOCVIEN
(
	MAHV CHAR(5),
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
	CONSTRAINT PK_MAHV PRIMARY KEY (MAHV),
)

CREATE TABLE LOP
(
	MALOP CHAR(3),
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO tinyint,
	MAGVCN CHAR(4),
	CONSTRAINT PK_MALOP PRIMARY KEY (MALOP),
	CONSTRAINT FK_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN (MAHV),
)


CREATE TABLE GIANGDAY
(
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	MAGV CHAR(4),
	HOCKY tinyint,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
)
CREATE TABLE KETQUATHI
(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LANTHI tinyint,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10)
)
USE QuanLyGiaoVu
-- Câu 1 --
ALTER TABLE HOCVIEN
ADD GHICHU CHAR(50), DIEMTB NUMERIC(4,2), XEPLOAI VARCHAR(10) 
--- CAU 2 ---
ALTER TABLE HOCVIEN 
ADD CONSTRAINT CHECK_MAHV CHECK(LEFT(MAHV,3)=MALOP)
--- CAU 3 ---
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GIOITINH CHECK (GIOITINH ='Nam' or GIOITINH = 'Nu')
--- CAU 5 ---
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KETQUATHI CHECK ((KQUA = 'Dat' AND DIEM >= 5 AND DIEM <= 10) or (KQUA= 'Khong dat' and DIEM<5) )
--- CAU 6 ---
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_LANTHI CHECK(LANTHI<=3)
--- CAU 7 ---
ALTER TABLE GIANGDAY 
ADD CONSTRAINT CK_HOCKY CHECK(HOCKY>=1 and HOCKY<=3)
--- CAU 8 ---
ALTER TABLE GIAOVIEN 
ADD CONSTRAINT CK_HOCVI CHECK(HOCVI='CN'or HOCVI='KS' or HOCVI ='Ths' or HOCVI='TS' or HOCVI='PTS')