USE QuanLyBanHang

--11.	Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày khách hàng đó đăng ký thành viên (NGDK).
CREATE TRIGGER TG_INSERT_NGHD ON HOADON 
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @COUNT INT = 0
	SELECT @COUNT = COUNT(*) FROM KHACHHANG,inserted WHERE KHACHHANG.MAKH = inserted.MAKH AND KHACHHANG.NGDK > inserted.NGHD
	IF(@COUNT > 0)
	BEGIN
		PRINT N'NGAY MUA HANG PHAI LON HOAC BANG NGAY DANG KI THANH VIEN'
		ROLLBACK TRAN
	END
	 
END

CREATE TRIGGER TG_INSERT_NGDK ON KHACHHANG
FOR UPDATE
AS 
BEGIN
	DECLARE @COUNT INT = 0
	SELECT @COUNT = COUNT(*) FROM HOADON,inserted WHERE HOADON.MAKH = inserted.MAKH AND HOADON.NGHD < inserted.NGDK
	IF(@COUNT > 0)
	BEGIN
		PRINT N'NGAY MUA HANG PHAI LON HOAC BANG NGAY DANG KI THANH VIEN'
		ROLLBACK TRAN
	END
END
SELECT * FROM HOADON
--12.	Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.
CREATE TRIGGER TRG_INS_UDT_NGHD ON HOADON
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @COUNT INT = 0
	SELECT @COUNT = COUNT(*) FROM NHANVIEN, inserted WHERE NHANVIEN.MANV = inserted.MANV AND NHANVIEN.NGVL > inserted.NGHD
	IF(@COUNT >0)
	BEGIN
		PRINT N'NGBH PHAI >= NGVL'
		ROLLBACK TRAN
	END
END

CREATE TRIGGER TG_UPT_NGVL
ON NHANVIEN
FOR UPDATE
AS
BEGIN
	DECLARE @COUNT INT = 0
	SELECT @COUNT = COUNT(*) 
					FROM HOADON, inserted
					WHERE HOADON.MANV = inserted.MANV
					AND HOADON.NGHD < inserted.NGVL
	IF(@COUNT > 0)
		BEGIN
			PRINT N'NGBL PHAI >= NGVL'
			ROLLBACK TRAN
		END
END
INSERT INTO HOADON VALUES(9919,'01/01/2005','KH01','NV01',320000)
--13.	Mỗi một hóa đơn phải có ít nhất một chi tiết hóa đơn.
CREATE TRIGGER TG_DEL_CTHD ON CTHD
FOR Delete
AS
BEGIN
	DECLARE @COUNT1 INT = 0
	DECLARE @COUNT2 INT = 0
	SELECT @COUNT1 = COUNT(*) FROM deleted
	SELECT @COUNT2 = COUNT(*) FROM HOADON, deleted WHERE deleted.SOHD = HOADON.SOHD
	IF (@COUNT1 = @COUNT2)
	BEGIN
		PRINT 'MOI HOA DON PHAI CO IT NHAT 1 CTHD'
		ROLLBACK TRANSACTION
	END
END

DELETE FROM CTHD WHERE SOHD = '1001' 

--14.	Trị giá của một hóa đơn là tổng thành tiền (số lượng*đơn giá) của các chi tiết thuộc hóa đơn đó.
INSERT INTO HOADON VALUES ('1024','2007-01-16', 'KH10','NV03',1000000)
SELECT *FROM HOADON WHERE SOHD=1024
CREATE TRIGGER TRIGIA_INSERT_HOADON
ON HOADON
FOR INSERT
AS
	DECLARE @SOHD INT
	SELECT @SOHD=SOHD FROM INSERTED

	UPDATE HOADON SET TRIGIA=0 WHERE SOHD=@SOHD
	PRINT('DA CAP NHAT TRI GIA =0 CHO HOA DON')

--TRIGGER UPDATE HOA DON
UPDATE HOADON SET TRIGIA=1000000 WHERE SOHD=1001	
SELECT * FROM HOADON WHERE SOHD =1001

CREATE TRIGGER TRIGIA_UPDATE_HOADON
ON HOADON
FOR UPDATE
AS
BEGIN
	DECLARE @SOHD INT, @TRIGIA MONEY
	SELECT @SOHD = SOHD FROM INSERTED
	SELECT @TRIGIA=SUM(SL*GIA) FROM CTHD,SANPHAM
	WHERE CTHD.MASP=SANPHAM.MASP
	AND SOHD=@SOHD


	UPDATE HOADON SET TRIGIA =@TRIGIA WHERE SOHD=@SOHD
	PRINT('DA CAP NHAT GIA TRI DUNG CHO HOA DON')
END

-- THEM CTHD

INSERT INTO CTHD VALUES(1001,'BB01',10)
SELECT * FROM HOADON WHERE SOHD=1001

CREATE TRIGGER TRIGIA_INSERT_CTHD
ON CTHD
FOR INSERT
AS 
BEGIN
	DECLARE @SOHD INT, @TRIGIA MONEY
	SELECT @SOHD = SOHD FROM INSERTED
	SELECT @TRIGIA=SUM(SL*GIA) FROM CTHD,SANPHAM
	WHERE CTHD.MASP=SANPHAM.MASP
	AND SOHD=@SOHD


	UPDATE HOADON SET TRIGIA =@TRIGIA WHERE SOHD=@SOHD
	PRINT('DA CAP NHAT GIA TRI DUNG CHO HOA DON')
END

--XOA CTHD
DELETE FROM CTHD WHERE SOHD=1001 AND MASP='BB01'
SELECT * FROM HOADON WHERE SOHD=1001
CREATE TRIGGER TRIGIA_DELETE_CTHD
ON CTHD
FOR DELETE
AS 
BEGIN
	DECLARE @SOHD INT, @TRIGIA MONEY
	SELECT @SOHD = SOHD FROM DELETED
	SELECT @TRIGIA=SUM(SL*GIA) FROM CTHD,SANPHAM
	WHERE CTHD.MASP=SANPHAM.MASP
	AND SOHD=@SOHD


	UPDATE HOADON SET TRIGIA =@TRIGIA WHERE SOHD=@SOHD
	PRINT('DA CAP NHAT GIA TRI DUNG CHO HOA DON')
END
--SUA CTHD

UPDATE CTHD SET SOHD=1002 WHERE SOHD=1001 AND MASP='ST01'
SELECT * FROM HOADON WHERE SOHD=1001 OR SOHD=1002

CREATE TRIGGER TRIGIA_UPDATE_CTHD
ON CTHD
FOR UPDATE
AS
BEGIN
	DECLARE @SOHDCU INT, @TRIGIAHDCU MONEY
	DECLARE @SOHDMOI INT, @TRIGIAHDMOI MONEY
	SELECT @SOHDCU=SOHD FROM DELETED
	SELECT @TRIGIAHDCU=SUM(SL*GIA) FROM CTHD,SANPHAM
	WHERE CTHD.MASP=SANPHAM.MASP
	AND SOHD=@SOHDCU

	SELECT @SOHDMOI=SOHD FROM INSERTED
	SELECT @TRIGIAHDMOI=SUM(SL*GIA) FROM CTHD,SANPHAM
	WHERE CTHD.MASP=SANPHAM.MASP
	AND SOHD=@SOHDMOI

	UPDATE HOADON SET TRIGIA=@TRIGIAHDCU WHERE SOHD=@SOHDCU
	UPDATE HOADON SET TRIGIA=@TRIGIAHDMOI WHERE SOHD=@SOHDMOI
	PRINT('DA CAP  NHAT TRI GIA CUA HOA DON')
END
--UPDATE SP
UPDATE SANPHAM SET GIA = 5000 WHERE MASP = 'TV01'
SELECT HOADON.SOHD, TRIGIA FROM CTHD, HOADON
WHERE CTHD.SOHD = HOADON.SOHD AND MASP = 'TV01'

CREATE TRIGGER TRIGIA_UPDATE_SANPHAM
ON SANPHAM
FOR UPDATE
AS
BEGIN
	DECLARE @MASP CHAR(4)
	SELECT @MASP = MASP FROM INSERTED

	SELECT * INTO TEMP FROM CTHD WHERE MASP=@MASP
	WHILE (EXISTS(SELECT *FROM TEMP))
	BEGIN
		DECLARE @SOHD INT, @TRIGIA MONEY
		SELECT TOP 1 @SOHD=SOHD FROM TEMP
		SELECT @TRIGIA=SUM(SL*GIA) FROM CTHD,SANPHAM
		WHERE CTHD.MASP=SANPHAM.MASP
		AND SOHD=@SOHD


		UPDATE HOADON SET TRIGIA =@TRIGIA WHERE SOHD=@SOHD
		DELETE FROM TEMP WHERE SOHD =@SOHD
	END
	DROP TABLE TEMP
	PRINT('DA CAP  NHAT TRI GIA CUA HOA DON')
END

USE QuanLyGiaoVu
--9.	Lớp trưởng của một lớp phải là học viên của lớp đó.
CREATE TRIGGER TG_INS_UPT_LOP
ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @COUNT INT = 0
	SELECT @COUNT = COUNT (*) FROM inserted, HOCVIEN
								WHERE inserted.MALOP = HOCVIEN.MALOP
								AND inserted.TRGLOP = HOCVIEN.MAHV
	IF (@COUNT = 0)
		BEGIN
			PRINT 'TRGLOP PHAI LA HV CUA LOP DÔ'
			ROLLBACK TRAN
		END
END

--10.	Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”.
CREATE TRIGGER TG_INS_UPT_KHOA
ON KHOA
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @COUNT INT = 0
	SELECT @COUNT = COUNT(*) FROM inserted, GIAOVIEN WHERE inserted.MAKHOA = GIAOVIEN.MAKHOA AND inserted.TRGKHOA = GIAOVIEN.MAGV AND GIAOVIEN.HOCVI IN ('TS','PTS')
	IF(@COUNT = 0)
	BEGIN
		PRINT 'ERROR: TRGKHOA PHAI LA GIAO VIEN THUOC KHOA VA CO HV LA TS HOAC PTS'
		ROLLBACK TRAN
	END
END
ALTER TABLE KHOA DROP FK_TRGKHOA
UPDATE KHOA SET TRGKHOA = 'GV99' WHERE MAKHOA = 'CNPM'
--15.	Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này.
CREATE TRIGGER INSERT_YPDATE_KETQUATHI_C15
ON	KETQUATHI
FOR	INSERT, UPDATE
AS
BEGIN
	DECLARE	@NGTHI	SMALLDATETIME,
			@DENNGAY	SMALLDATETIME

	SELECT	@NGTHI=NGTHI,@DENNGAY=DENNGAY
	FROM		INSERTED A,HOCVIEN B, GIANGDAY C
	WHERE	A.MAHV=B.MAHV AND B.MALOP=C.MALOP AND A.MAMH=C.MAMH
	
	IF(@NGTHI>@DENNGAY)
		PRINT 'SUCCESSFUL!KETQUATHI HOP LE.'
	ELSE
		BEGIN
			ROLLBACK TRAN
			PRINT 'ERROR!LOP CUA HV CHUA HOC XONG MON NAY'
		END
END
	--------
CREATE TRIGGER UPDATE_GIANGDAY_C15
ON	GIANGDAY
FOR	UPDATE
AS
BEGIN
	DECLARE	@NGTHI	SMALLDATETIME,
			@DENNGAY	SMALLDATETIME

	SELECT	@DENNGAY=DENNGAY
	FROM		INSERTED
	
	IF(@DENNGAY<ALL (SELECT	NGTHI
				  FROM	INSERTED A,HOCVIEN B, KETQUATHI C
				  WHERE	A.MALOP=B.MALOP AND B.MAHV=C.MAHV AND A.MAMH=C.MAMH))
		PRINT 'SUCCESSFUL!THOA YEU CAU DENNGAY<NGTHI'
	ELSE
		BEGIN
			ROLLBACK TRAN
			PRINT 'ERROR!ANH HUONG DEN KETQUATHI, NGAY_KET_THUC PHAI TRUOC HON NGAYTHI.'
		END	
END
--16.	Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.
CREATE TRIGGER INSERT_UPDATE_GIANGDAY_C16
ON	GIANGDAY
FOR	INSERT, UPDATE
AS
BEGIN
	DECLARE	@SL_MONHOC	INT

	SELECT	@SL_MONHOC=COUNT(A.MAMH)
	FROM		GIANGDAY A, INSERTED B
	WHERE	A.MALOP=B.MALOP AND A.HOCKY=B.HOCKY AND A.NAM=B.NAM

	IF(@SL_MONHOC=4)
		BEGIN
			ROLLBACK TRAN
			PRINT 'ERROR!LOP NAY DA HOC HON 3 MON TRONG CUNG HOCKY, NAM'
		END
END
--17.	Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó.
CREATE TRIGGER INSERT_LOP_C17
ON LOP 
FOR	INSERT
AS
BEGIN
	UPDATE	LOP
	SET		SISO=0
	WHERE	MALOP=(SELECT	MALOP
				  FROM	INSERTED)
END
	----------
CREATE TRIGGER UPDATE_LOP_C17
ON LOP 
FOR	UPDATE
AS
BEGIN
	UPDATE	LOP
	SET		SISO=(SELECT	SISO
				 FROM	DELETED)
	WHERE	MALOP=(SELECT	MALOP
				  FROM	INSERTED)
END
	--------------
CREATE TRIGGER INSERT_HOCVIEN_C17
ON	HOCVIEN
FOR	INSERT
AS
BEGIN
	UPDATE	LOP
	SET		SISO=SISO+1
	WHERE	MALOP=(SELECT	MALOP
				  FROM	INSERTED)
END
	------------
CREATE TRIGGER DELETE_HOCVIEN_C17
ON	HOCVIEN
FOR	DELETE
AS
BEGIN
	DECLARE	@MAHV		CHAR(5),
			@TRGLOP		CHAR(5),
			@MALOP		CHAR(3)

	SELECT	@MAHV=MAHV, @TRGLOP=TRGLOP, @MALOP=A.MALOP
	FROM		DELETED A, LOP B
	WHERE	A.MALOP=B.MALOP
	
	UPDATE	LOP
	SET		SISO=SISO-1
	WHERE	MALOP=@MALOP
END
	-------------
CREATE TRIGGER UPDATE_HOCVIEN_C17
ON	HOCVIEN
FOR	UPDATE
AS
BEGIN
	UPDATE	LOP
	SET		SISO=SISO+1
	WHERE	MALOP=(SELECT	MALOP
				  FROM	INSERTED)
	UPDATE	LOP
	SET		SISO=SISO-1
	WHERE	MALOP=(SELECT	MALOP
				  FROM	DELETED)
END
--18.	Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong cùng một bộ không được giống nhau (“A”,”A”) và cũng không tồn tại hai bộ (“A”,”B”) và (“B”,”A”).
CREATE TRIGGER INSERT_UPDATE_C18
ON	DIEUKIEN
FOR	INSERT, UPDATE
AS
BEGIN
	DECLARE	@MAMH		VARCHAR(10),
			@MAMH_TRUOC	VARCHAR(10)

	SELECT	@MAMH=MAMH, @MAMH_TRUOC=MAMH_TRUOC
	FROM		INSERTED

	IF((@MAMH=@MAMH_TRUOC)OR
	   (@MAMH IN (SELECT	MAMH_TRUOC
				FROM		DIEUKIEN
				WHERE	MAMH=@MAMH_TRUOC))OR
	   (@MAMH_TRUOC IN (SELECT	MAMH
					FROM		DIEUKIEN
					WHERE	MAMH_TRUOC=@MAMH)))
		BEGIN
			ROLLBACK TRAN
			PRINT 'DIEUKIEN KO HOP LE'
		END
END
--19.	Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau.
CREATE TRIGGER INSERT_UPDATE_GIAOVIEN_C19
ON	GIAOVIEN
FOR	INSERT, UPDATE
AS
BEGIN
	DECLARE	@MUCLUONG		MONEY,
			@MAGV		CHAR(4)
	
	SELECT	DISTINCT @MUCLUONG=A.MUCLUONG,@MAGV=B.MAGV
	FROM		GIAOVIEN A, INSERTED B
	WHERE	A.HOCHAM=B.HOCHAM AND A.HOCVI=B.HOCVI AND A.HESO=B.HESO AND A.MAGV<>B.MAGV
	
	UPDATE	GIAOVIEN
	SET		MUCLUONG=@MUCLUONG	
	WHERE	MAGV=@MAGV
END
--20.	Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5.
CREATE TRIGGER INSERT_UPDATE_KETQUATHI_C20
ON		KETQUATHI
FOR		INSERT, UPDATE
AS
BEGIN
	DECLARE	@LANTHI	INT,
			@DIEM	NUMERIC(4,2)
		
	SELECT	@LANTHI=LANTHI
	FROM		INSERTED

	IF(@LANTHI>1)
		BEGIN
			SELECT	@DIEM=B.DIEM
			FROM		INSERTED A,KETQUATHI B
			WHERE	A.MAHV=B.MAHV AND A.MAMH=B.MAMH AND B.LANTHI=@LANTHI-1

			IF(@DIEM>=5)
				BEGIN
					ROLLBACK TRAN
					PRINT 'HV NAY DA THI DAT'
				END
		END
	DELETE FROM	KETQUATHI
	WHERE	LANTHI>@LANTHI
END
--21.	Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước (cùng học viên, cùng môn học).
--22.	Học viên chỉ được thi những môn mà lớp của học viên đó đã học xong.
--23.	Khi phân công giảng dạy một môn học, phải xét đến thứ tự trước sau giữa các môn học (sau khi học xong những môn học phải học trước mới được học những môn liền sau).
--24.	Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách.
CREATE TRIGGER INSERT_GIANGDAY_C24
ON	GIANGDAY
FOR	INSERT, UPDATE
AS
BEGIN
	DECLARE	@MAKHOA1	CHAR(4),
			@MAKHOA2	CHAR(4)

	SELECT	@MAKHOA1=B.MAKHOA, @MAKHOA2=C.MAKHOA
	FROM		INSERTED A, MONHOC B, GIAOVIEN C
	WHERE	A.MAMH=B.MAMH AND A.MAGV=C.MAGV

	IF(@MAKHOA1<>@MAKHOA2)
		BEGIN
			ROLLBACK TRAN
			PRINT 'ERROR!MAMH PHAI THUOC KHOA GIAO VIEN PHU TRACH'
		END
	ELSE
		PRINT 'SUCCESSFUL'
END
